---
downloads: ~/.ansible-downloads/

configure_ansible: no
configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: no
configure_osx: no

dotfiles_repo: git@github.com:moisesguimaraes/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  #- .bash_profile
  - .gitconfig
  - .gitignore
  - .gitextras
  #- .inputrc
  #- .osx
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  - autoconf
  - automake
  - git-review
  - libtool
  - pyenv
  - pyenv-virtualenv
  - pyenv-virtualenvwrapper
  - wireshark
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  ## backup
  - dropbox
  ## games
  # battle-net
  - openemu
  - steam
  ## tools
  - diffmerge
  - focus-booster
  - iterm2
  - sourcetree
  - textmate
  ## browsers
  - firefox
  - google-chrome
  ## virtualization
  - docker
  - vagrant
  - virtualbox
  # vmware-fusion
  ## others
  - libreoffice
  - skype
  - supercollider

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 443987910, name: "1Password" }
  - { id: 803453959, name: "Slack" }
  - { id: 747648890, name: "Telegram" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 408981434, name: "iMovie" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - tasks/ohmyzsh.yml
  - tasks/pyenv.yml

pyenv_versions:
  - 3.7.0
  - 2.7.15

pyenv_virtualenvs:
  - name: jupyter3
    version: 3.7.0
    packages:
      - jupyter
    post: "python -m ipykernel install --user"
  - name: tools3
    version: 3.7.0
    packages: []
    post: ""
  - name: ipython2
    version: 2.7.15
    packages:
      - ipykernel
    post: "python -m ipykernel install --user"
  - name: tools2
    version: 2.7.15
    packages: []
    post: ""
