---
downloads: ~/.ansible-downloads/

#
# global togglers
#

configure_homebrew:       yes
configure_ansible:        yes
configure_dotfiles:       yes
configure_extra_packages: yes
configure_mas:            yes
configure_sudoers:        no
configure_terminal:       no
configure_osx:            no

#
# dotfiles
#

dotfiles_repo: git@github.com:moisesguimaraes/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dotfiles

dotfiles_files:
  # bin/brew
  - bin/hack
  - bin/ship
  - bin/dwf
  - Library/Application Support/Code/User/settings.json
  - .config/kitty/kitty.conf
  - .gitconfig
  - .gitconfig.redhat
  - .gitconfig.wolfssl
  - .gitignore
  # .osx
  - .vimrc
  - .zshrc
  - .zsh_theme_config

#
# homebrew
#

homebrew_taps:
  - homebrew/bundle
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - heroku/brew

homebrew_installed_packages:
  ## c
  - autoconf
  - automake
  - libtool
  ## python
  - black
  - flake8
  - pyenv
  - pyenv-virtualenv
  - pyenv-virtualenvwrapper
  - tox
  ## git
  - git-review
  - pre-commit
  ## chat
  - weechat
  ## images
  - exiftool
  ## videos
  - ffmpeg
  ## security
  - gnupg
  ## tools
  - tmate

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  ## backup & identity
  - dropbox
  - keybase
  ## games
  # battle-net
  - cockatrice
  - epic-games
  - openemu
  - steam
  ## terminal
  - kitty
  ## tools
  - diffmerge
  - textmate
  - visual-studio-code
  - wireshark
  ## browsers
  - firefox
  - google-chrome
  - flash-npapi
  ## virtualization
  - docker
  - vagrant
  - vagrant-manager
  - virtualbox
  ## fonts
  - font-fira-code
  - font-overpass
  ## productivity
  # focus-booster
  # graphviz
  - imagealpha
  - libreoffice
  - openscad
  ## music
  - spotify
  - supercollider
  ## social
  - discord
  - skype
  ## network
  - tunnelblick

#
# mas
#

mas_installed_apps:
  - { id: 443987910,  name: "1Password" }
  - { id: 1333542190, name: "1Password 7" }
  - { id: 1432731683, name: "Adblock Plus" }
  - { id: 1480070821, name: "Cyph" }
  - { id: 803453959,  name: "Slack" }
  - { id: 409183694,  name: "Keynote" }
  - { id: 409201541,  name: "Pages" }
  - { id: 409203825,  name: "Numbers" }
  - { id: 408981434,  name: "iMovie" }
  - { id: 682658836,  name: "GarageBand" }
  - { id: 411643860,  name: "DaisyDisk" }
  - { id: 638161122,  name: "YubiKey Personalization Tool" }
  - { id: 1116599239, name: "NordVPN IKE" }

#
# osx
#

osx_script: "~/.osx --no-restart"

#
# extra packages
#

composer_packages: []

gem_user_install: yes

gem_packages:
  - name: bundler
    state: latest

npm_packages: []

pip_packages: []

#
# extra tasks
#

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - tasks/ohmyzsh.yml
  - tasks/pyenv.yml
  - tasks/vscode.yml

#
# pyenv
#

pyenv_versions:
  - 3.8.5
  - 2.7.18

pyenv_virtualenvs:
  - name: jupyter3
    version: 3.8.5
  - name: tools3
    version: 3.8.5
  - name: ipython2
    version: 2.7.18
  - name: tools2
    version: 2.7.18

pyenv_global:
  - 3.8.5
  - 2.7.18
  - jupyter3
  - ipython2
  - tools3
  - tools2

pyenv_virtualenv_packages:
  - env: tools2
    name: six
#  - name: jupyter
#    env: jupyter3
#    post: "python -m ipykernel install --user"
#  - name: flake8
#    env: tools3
#  - name: tox
#    env: tools3
#  - name: ipykernel
#    env: ipython2
#    post: "python -m ipykernel install --user"

#
# vscode
#

vscode_extensions:
  - ms-python.python
  - PKief.material-icon-theme
  - vangware.dark-plus-material
  - EditorConfig.EditorConfig
  - dunstontc.viml
