---
downloads: ~/.ansible-downloads/

#
# global togglers
#

configure_homebrew:       true
configure_ansible:        true
configure_dotfiles:       true
configure_extra_packages: true
configure_mas:            true
configure_sudoers:        false
configure_terminal:       false
configure_osx:            false

sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

#
# dotfiles
#

dotfiles_repo: git@github.com:moisesguimaraes/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/dotfiles

dotfiles_files:
  # bin/brew
  - bin/hack
  - bin/ship
  - bin/dwf
  - Library/Application Support/Code/User/settings.json
  - Library/KeyBindings/DefaultKeyBinding.dict
  - .config/kitty/kitty.conf
  - .gitconfig
  - .gitconfig.redhat
  - .gitconfig.wolfssl
  - .gitignore
  # .osx
  - .vimrc
  - .zshrc
  - .zsh_theme_config

#
# homebrew
#

homebrew_installed_packages:
  ## c
  - autoconf
  - automake
  - libtool
  ## python
  - black
  - flake8
  - pyenv
  - pyenv-virtualenv
  - pyenv-virtualenvwrapper
  - tcl-tk
  - tox
  ## git
  - git-review
  - pre-commit
  ## chat
  - weechat
  ## images
  - exiftool
  - imagemagick
  ## videos
  - ffmpeg
  ## security
  - gnupg
  ## tools
  - tmate
  ## deployment
  - awscli
  - heroku

homebrew_taps:
  # homebrew/bundle
  - homebrew/core
  - homebrew/cask
  # homebrew/cask-fonts
  # heroku/brew

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  ## backup & identity
  - dropbox
  - keybase
  ## games
  # battle-net
  - cockatrice
  - epic-games
  - openemu
  - steam
  ## terminal
  - kitty
  ## tools
  - diffmerge
  - textmate
  - visual-studio-code
  - wireshark
  ## browsers
  # firefox
  # google-chrome
  ## virtualization
  - docker
  - vagrant
  - vagrant-manager
  - virtualbox
  ## fonts
  - font-fira-code
  - font-overpass
  ## productivity
  # focus-booster
  # graphviz
  - imagealpha
  - libreoffice
  - openscad
  ## music
  # blackhole
  - spotify
  - supercollider
  ## video
  - obs
  ## social
  - discord
  - skype
  ## network
  - tunnelblick

#
# mas
#

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  # { id: 443987910,  name: "1Password" }
  - { id: 1333542190, name: "1Password 7" }
  - { id: 1432731683, name: "Adblock Plus" }
  # { id: 1480070821, name: "Cyph" }
  # { id: 803453959,  name: "Slack" }
  # { id: 409183694,  name: "Keynote" }
  # { id: 409201541,  name: "Pages" }
  # { id: 409203825,  name: "Numbers" }
  # { id: 408981434,  name: "iMovie" }
  # { id: 682658836,  name: "GarageBand" }
  - { id: 411643860,  name: "DaisyDisk" }
  - { id: 638161122,  name: "YubiKey Personalization Tool" }
  - { id: 1116599239, name: "NordVPN IKE" }
mas_email: ""
mas_password: ""

#
# osx
#

osx_script: "~/.osx --no-restart"

#
# extra packages
#

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A

gem_user_install: yes

gem_packages:
  - name: bundler
    state: latest

npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A

pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

#
# extra tasks
#

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - tasks/ohmyzsh.yml
  - tasks/pyenv.yml
  - tasks/vscode.yml

#
# pyenv
#

pyenv_versions:
  - 3.9.1
  - 3.8.7
  - 3.6.13
  - 2.7.18

pyenv_virtualenvs:
  - name: jupyter3
    version: 3.9.1
  - name: tools3
    version: 3.9.1
  - name: ipython2
    version: 2.7.18
  - name: tools2
    version: 2.7.18

pyenv_global:
  - 3.9.1
  - 3.8.7
  - 3.6.13
  - 2.7.18
  - jupyter3
  - ipython2
  - tools3
  - tools2

pyenv_virtualenv_packages:
  - env: tools2
    name: six
#  - name: jupyter
#    env: jupyter3
#    post: "python -m ipykernel install --user"
#  - name: flake8
#    env: tools3
#  - name: tox
#    env: tools3
#  - name: ipykernel
#    env: ipython2
#    post: "python -m ipykernel install --user"

#
# vscode
#

vscode_extensions:
  - ms-python.python
  - PKief.material-icon-theme
  - vangware.dark-plus-material
  - EditorConfig.EditorConfig
  - dunstontc.viml
