---
downloads: ~/.ansible-downloads/

configure_homebrew:       yes
configure_ansible:        yes
configure_dotfiles:       yes
configure_extra_packages: yes
configure_mas:            yes
configure_sudoers:        no
configure_terminal:       no
configure_osx:            no

dotfiles_repo: git@github.com:moisesguimaraes/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Dropbox/Workstation/dotfiles

dotfiles_files:
  #- .bash_profile
  - bin
  - .config
  - .gitconfig
  - .gitignore
  #- .inputrc
  #- .osx
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  - autoconf
  - automake
  - git-review
  - libtool
  - pyenv
  - pyenv-virtualenv
  - pyenv-virtualenvwrapper
  - weechat
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - caskroom/fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  ## backup & identity
  - dropbox
  - keybase
  ## games
  # battle-net
  - openemu
  - steam
  ## tools
  - diffmerge
  - focus-booster
  - kitty
  - iterm2
  - sourcetree
  - textmate
  - visual-studio-code
  - wireshark
  ## browsers
  - firefox
  - google-chrome
  ## virtualization
  # docker
  # vagrant
  # virtualbox
  # vmware-fusion
  ## fonts
  - font-fira-code
  ## others
  # graphviz
  - libreoffice
  - skype
  - supercollider
  ## redhat
  - tunnelblick

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 443987910, name: "1Password" }
  - { id: 803453959, name: "Slack" }
  - { id: 747648890, name: "Telegram" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 408981434, name: "iMovie" }
  - { id: 682658836, name: "GarageBand" }
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 638161122, name: "YubiKey Personalization Tool" }
  - { id: 410628904, name: "Wunderlist: To-Do List & Tasks" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_user_install: yes
gem_packages:
  - name: bundler
    state: present # present/absent/latest, default: present
  # version: "~> 1.15.1" # default: N/A
  - name: jekyll
    state: present
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - tasks/ohmyzsh.yml
  - tasks/pyenv.yml

pyenv_versions:
  - 3.7.1
  - 3.5.6
  - 2.7.15

pyenv_virtualenvs:
  - name: jupyter3
    version: 3.7.1
    packages:
      - jupyter
    post: "python -m ipykernel install --user"
  - name: tools3
    version: 3.7.1
    packages:
      - flake8
      - tox
    post: ""
  - name: ipython2
    version: 2.7.15
    packages:
      - ipykernel
    post: "python -m ipykernel install --user"
  - name: tools2
    version: 2.7.15
    packages: []
    post: ""

pyenv_global:
  - 3.7.1
  - 2.7.15
  - jupyter3
  - ipython2
  - tools3
  - tools2
