---
- name: Ensure workon directory exists.
  file:
    path: ~/.ve
    state: directory

- name: Ensure workspace directory exists.
  file:
    path: ~/workspaces
    state: directory

- name: List installed python versions.
  command: pyenv versions
  register: installed_pyenvs
  check_mode: no
  changed_when: false

- name: Setting variable for CFLAGS.
  command: "xcrun --show-sdk-path"
  register: osx_sdk_dir

- name: Ensure configured python versions are installed.
  command: pyenv install {{ item }}
  environment:
    CFLAGS: -I{{osx_sdk_dir.stdout}}/usr/include
  with_items: "{{ pyenv_versions }}"
  when: item not in installed_pyenvs.stdout

- name: Ensure configured virtualenvs are created.
  command: pyenv virtualenv {{ item.version }} {{ item.name }}
  with_items: "{{ pyenv_virtualenvs }}"
  when: item.name not in installed_pyenvs.stdout

- name: Ensure pyenv global is set.
  command: pyenv global {{ pyenv_global | join(' ') }}

- name: Ensures ipython profile dir exists
  file:
    path: ~/.ipython/profile_default/startup
    state: directory

- name: Ensures ipython profile exists
  template:
    src: files/ipython/00-venv-sitepackages.py
    dest: ~/.ipython/profile_default/startup/00-venv-sitepackages.py