---
- name: List installed vscode extensions.
  command: code --list-extensions
  register: installed_vscode_extensions
  check_mode: no
  changed_when: false

- name: Ensure configured vscode extensions are installed.
  command: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  when: item not in installed_vscode_extensions.stdout
